### PR TITLE
[GLUE-312] Custom Elements for Crumb (react-router Link support)

### PR DESCRIPTION
**Pull request by brock-noah**
### Issue
It would be nice to use the `Link` component with the `to` prop rather than something like
```
<Crumb onClick={e => routerProps.history.push('to')}>
```
Cannot pass `Link` as a child because causes double `a` tags and incorrect styles.

### Change Log
- add `Crumb.props.element`

React Router Link [supports](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L76) this because it spreads the props and returns an `a`

### Discussion Topics:
- Should the component support this? Or should we force the use of `routerProps.history.push`
- Is there a naming convention for this feature? Should the prop be called `element`, `component`, `tag`, etc.

# Testing Requirements
- [ ] Breadcrumbs act normally

### CODE REVIEW

**Comment by farism** [comment]
Crumb should probably always render a span, and we should break BEM in the css to target `a` kind of like we did with `.tabs_link`

**Comment by brock-noah** [comment]
What about cloning the children to apply the class name?
```
React.cloneElement(children, { className: cx('crumb', children.props.className) })
```

**Comment by janamcclure** [comment]
should this go into testing?

**Comment by farism** [comment]
We're going to address this the way we did with `tab_link` and targetting `a`.

**Pull request closed without merging**
