### PR TITLE
Breadcrumb Height Changing

### PR DESCRIPTION
**Pull request by brock-noah**
Add line height so when going from 1 to 2 or 2 to 1 crumbs the box doesn't change.
Introduction of core-icons caused this issue.

## Before
crumb change

## After
crumb change good

### CODE REVIEW

**Comment by janamcclure** [comment]
ill test this now, thanks!

**Comment by janamcclure** [comment]
passed testing. I dont have setup to regress up a breadcrumb outside of the docs, but no styles broke...

**Comment by janamcclure** [comment]
actually i just removed the other tabs in the code on the react doc site and was able to replicate the issue on master and confirmed that this did fix it!

**Comment by farism** [comment]
Would a static height flex container with vertically centered elements make more sense?

**Pull request merged**
