### PR TITLE
Docs - Inject version from Webpack and fetch published versions

### PR DESCRIPTION
**Pull request by remyyounes**
https://procoretech.atlassian.net/browse/ISSUE_ID

### Change Log
- Inject build version as a process.env variable instead of scraping the url
- fetch and save NPM version list
- Documentation Version picker fetches version list instead of hard coded values

### Next Steps
1. Should we only save one version list since all our packages versions are tied together?

### Screenshots
screen shot 2018-01-01 at 4 31 13 pm

# Testing Requirements
- [ ] Version picker defaults to current version
- [ ] Version picker lists all stable versions ( non-retroactive )

### CODE REVIEW

**Comment by dannyphillips** [comment]
Looks great. The other thing we need to do is ensure each doc version uses the correct version of each package. For a while core-react docs were always pointing to latest for core-css. This may have already been resolved though

**Comment by farism** [comment]
Do we need this on icons as well?

**Comment by dannyphillips** [comment]
Yes, lets only use one `versions.json` file

**Comment by dannyphillips** [comment]
@faris yes we do. Some icons won't be available in older versions and we may want to show that in the docs.

**Pull request merged**
