### PR TITLE
[Hotfix] Fix Core-Icons Docs

### PR DESCRIPTION
**Pull request by dannyphillips**
https://procoretech.atlassian.net/browse/ISSUE_ID
### Change Log
-rename demo.html to index.html for core-icons

# Testing Requirements
- [ ] Core-Icons docs work at https://procore.github.io/core/3.0.1/icons/

### CODE REVIEW

**Comment by dannyphillips** [comment]
I might have to go in by hand and fix the old versions on gh-pages.

**Comment by janamcclure** [comment]
i dont think i can test this without it being merged?

**Comment by janamcclure** [comment]
@dannyphillips  could you please provide me with notes on how to test this locally?

**Comment by dannyphillips** [comment]
This has to be tested in production, but can be confirmed by visiting teh following links: 

Bad Icons Url: https://procore.github.io/core/3.0.1/icons/
Fixed Icons Url: https://procore.github.io/core/3.0.2-hotfix.0/icons/

**Pull request merged**
