### PR TITLE
rename alerts to toasts

### PR DESCRIPTION
**Pull request by janamcclure**
change alert to toasts to prevent confusion with confirmation dialogue. they are now going to act as toasts and no longer appear in the header but rather at the bottom of the page. marcus is creating a corresponding particle for that behavior.

### CODE REVIEW

**Comment by dannyphillips** [comment]
My only concern with this change, is there any way to build a non-dismissable banner in the header?

**Comment by dannyphillips** [comment]
I'm thinking about things like "upcoming maintenance windows" or "outages" or "trial access"

**Comment by janamcclure** [comment]
banners should be non dismissible by default. we currently support both i the docs. i do want to do a follow up to redo the way we display them and name them so that default is without dismiss...

**Comment by janamcclure** [comment]
do not merge, styles are not rendering correctly on core/react for toasts. on hold until that is resolved.

**Comment by janamcclure** [comment]
closing to rework in a different branch.

**Pull request closed without merging**
