### PR TITLE
Add New Icons to React Map

### PR DESCRIPTION
**Pull request by brock-noah**
### Change Log
- in core-icons but not core-react

### Discussion Topics:
- is this map necessary?

# Testing Requirements
- [ ] each of the 4 can be used

### CODE REVIEW

**Comment by farism** [comment]
I think the map is necessary because we want to output the enum list in our docs. However, styleguidist is janky and doesn't even show it atm (won't show until we move to stylegator). 

I'm also considering exposing the `selection.json` from `core-icons`, importing that, and auto-generating this list.

Thoughts?

**Comment by mboperator** [comment]
I like the autogeneration idea. I also think we should just pass the string through if it's not present in the map.

**Comment by brock-noah** [comment]
For passing the string through, should we append `ci-`?

**Comment by farism** [comment]
> For passing the string through, should we append ci-?

ya

**Pull request merged**
