### PR TITLE
Avatar Fixed Size

### PR DESCRIPTION
**Pull request by brock-noah**
I used an avatar as a direct child of a flex container. The avatar was being squished, causing an oval. While I could add another markup layer around the avatar, I feel this will prevent others from running into this issue.

### CODE REVIEW

**Comment by farism** [comment]
> While I could add another markup layer around the avatar, I feel this will prevent others from running into this issue.

I think this is the better approach. I think this would be a problem with any element that has fixed dimension(s). If we go with this approach, would we want to add it to all elements with fixed dimensions?

**Comment by brock-noah** [comment]
Good question. Anything that relies on `height` or `width` properties are exposed to this 'bug' / knowledge requirement, while padding setting the size is not. It sounds like in the name "fixed dimension" it shouldn't flex.

**Comment by remyyounes** [comment]
@brock-noah could you paste or link to your usecase?

**Comment by brock-noah** [comment]
@remyyounes https://github.com/procore/my-procore/blob/efab40083bde536569715cc69520490556a17c96/app/javascript/packs/routes/Settings/Favorites/Favorite.jsx#L59-L70

**Pull request merged**
